/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NameRouteImport } from './routes/$name'
import { Route as GithubCallbackRouteImport } from './routes/github.callback'
import { Route as OauthCallbackRouteImport } from './routes/oauth.callback'
import { Route as XCallbackRouteImport } from './routes/x.callback'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NameRoute = NameRouteImport.update({
  id: '/$name',
  path: '/$name',
  getParentRoute: () => rootRouteImport,
} as any)
const GithubCallbackRoute = GithubCallbackRouteImport.update({
  id: '/github/callback',
  path: '/github/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthCallbackRoute = OauthCallbackRouteImport.update({
  id: '/oauth/callback',
  path: '/oauth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const XCallbackRoute = XCallbackRouteImport.update({
  id: '/x/callback',
  path: '/x/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$name': typeof NameRoute
  '/github/callback': typeof GithubCallbackRoute
  '/oauth/callback': typeof OauthCallbackRoute
  '/x/callback': typeof XCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$name': typeof NameRoute
  '/github/callback': typeof GithubCallbackRoute
  '/oauth/callback': typeof OauthCallbackRoute
  '/x/callback': typeof XCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$name': typeof NameRoute
  '/github/callback': typeof GithubCallbackRoute
  '/oauth/callback': typeof OauthCallbackRoute
  '/x/callback': typeof XCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/$name' | '/github/callback' | '/oauth/callback' | '/x/callback'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$name' | '/github/callback' | '/oauth/callback' | '/x/callback'
  id:
    | '__root__'
    | '/'
    | '/$name'
    | '/github/callback'
    | '/oauth/callback'
    | '/x/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NameRoute: typeof NameRoute
  GithubCallbackRoute: typeof GithubCallbackRoute
  OauthCallbackRoute: typeof OauthCallbackRoute
  XCallbackRoute: typeof XCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$name': {
      id: '/$name'
      path: '/$name'
      fullPath: '/$name'
      preLoaderRoute: typeof NameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/github/callback': {
      id: '/github/callback'
      path: '/github/callback'
      fullPath: '/github/callback'
      preLoaderRoute: typeof GithubCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth/callback': {
      id: '/oauth/callback'
      path: '/oauth/callback'
      fullPath: '/oauth/callback'
      preLoaderRoute: typeof OauthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/x/callback': {
      id: '/x/callback'
      path: '/x/callback'
      fullPath: '/x/callback'
      preLoaderRoute: typeof XCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NameRoute: NameRoute,
  GithubCallbackRoute: GithubCallbackRoute,
  OauthCallbackRoute: OauthCallbackRoute,
  XCallbackRoute: XCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
